<a href="https://colab.research.google.com/github/jasvir-kaur-108/ML_basic/blob/main/sklinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
data = pd.read_csv("Student_Performance.csv")

In [ ]:
df = pd.DataFrame(data)
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [ ]:
x =df['Previous Scores']
y =df['Performance Index']

In [ ]:
x_train ,y_train,x_test,y_test = train_test_split(x,y ,test_size=0.25, random_state=42)

In [ ]:
x_train.shape,y_train.shape,y_test.shape,x_test.shape

((7500, 5), (2500, 5), (2500,), (7500,))

In [ ]:
lr = LinearRegression()
lr.fit(x_train, y_train)

ValueError: Found input variables with inconsistent numbers of samples: [7500, 2500]

In [ ]:
y_pred = lr.predict([x_test])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [ ]:
#r2_score(y_test, y_pred)

df['Extracurricular Activities']=df['Extracurricular Activities'].map({
    'Yes':1,
    'No':0
})
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [ ]:
x = df.drop(['Performance Index'], axis=1)
y = df['Performance Index']

In [ ]:
mean_squared_error([y_test], [y_pred])**0.5

ValueError: Found array with dim 3. None expected <= 2.

r= (y_act -y_pred)**2

In [ ]:
r=((y_act - y_pred)**2).mean()

NameError: name 'y_act' is not defined

In [ ]:
import numpy as np

In [ ]:
np.cbrt(mean_squared_error(y_test, y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [2500, 1]